name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: "25 22 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          toolchain: stable

      - name: Check formatting
        run: cargo fmt --check

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy